class Const:
    HW = 512
    H = 512
    W = 512
    LATENT_SIZE = (64, 64)
    BATCH_SIZE = 1

    NUM_INFERENCE_STEPS = 100  # Number of inference steps in mask evolution
    NUM_STATIC_INFERENCE_STEPS = 100  # Number of inference steps in final runs
    BLENDING_START_PERCENTAGE = 0.25
    DYN_START = 0.2
    DYN_COND_STOP = 0.25
    DYN_FINAL_STOP = 0.3

    N_OUTS_FOR_DYN_MASK = 8
    N_RUNS_ON_SCORES = 2
    N_AUGS_ON_SCORES = 32
    AUG_NUM = 2

    POTENTIAL_PEAK = 0.08
    SIGMA_FOR_SHAPE64 = 10.0
    BIAS_DILATION_VAL = 0.6
    BIAS_DILATION_DEC_FACTOR = 0.94
    ADDITION_IN_COLLAPSE = 0.3
    POINT_ON_LATENT_RADIUS = 1.7
    OUT_RING_WIDTH = 3
    IN_ON_RING_WIDTH = 6
    GUIDANCE_SCALE = 14.0
    THRESH_VAL = 0
    MASK_LR = 4.0
    RERUN_MAX_AREA_RATIO_FOR_DILATION = 0.2
    MAX_AREA_RATIO_FOR_DILATION = 0.02
    ALPHA_MASK_DILATION_ON_512 = 40
    RERUN_STOP_DILATION = 4

    GAUSS_K_GRADS = 3
    GAUSS_SIGMA_GRADS = 1
    GAUSS_K_MASK = 5
    GAUSS_SIGMA_MASK = 1
    GAUSS_K_THRESHED = 7
    GAUSS_SIGMA_THRESHED = 3
    THRESH_POST_GAUSS = 0.45
    CLOSE_GAPS_WITH_CONNECTION_THICKNESS = 3
    CLOSING_K = 3
    BACK_PRES_SIGMA = 25
    BACK_PRES_SCALE = 20

    MAX_SEED = 2**32 - 1


class N:
    POTENTIAL = "potential"
    LATENT_MASK = "latent_mask"
